cabal-version:      3.4
name:               storyflow-md
version:            0.1.0.0
synopsis:           story-flow 的 Markdown 分節格式雙向轉換
license:            BSD-3-Clause
author:             Alchbees Studio
maintainer:         lhm.stu@gmail.com
build-type:         Simple

common warnings
    ghc-options: -Wall -Wcompat

common lang
    default-language:   GHC2021
    default-extensions:
        DerivingStrategies
        LambdaCase
        OverloadedStrings
        RecordWildCards
        StrictData

library
    import:           warnings, lang
    hs-source-dirs:   src
    exposed-modules:
        StoryFlow.Md
    build-depends:
        , base       >=4.14 && <5
        , storyflow-core
        , text

test-suite storyflow-md-test
    import:           warnings, lang
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Spec.hs
    other-modules:
        StoryFlow.MdSpec
    build-depends:
        , base
        , hspec
        , storyflow-core
        , storyflow-md
        , text
