cabal-version:      3.4
name:               storyflow-store
version:            0.1.0.0
synopsis:           story-flow 的檔案落地與 SQLite 索引
license:            BSD-3-Clause
author:             Alchbees Studio
maintainer:         lhm.stu@gmail.com
build-type:         Simple

common warnings
    ghc-options: -Wall -Wcompat

common lang
    default-language:   GHC2021
    default-extensions:
        DerivingStrategies
        LambdaCase
        OverloadedStrings
        RecordWildCards
        StrictData

library
    import:           warnings, lang
    hs-source-dirs:   src
    exposed-modules:
        StoryFlow.Store
        StoryFlow.Store.Atomic
        StoryFlow.Store.Create
        StoryFlow.Store.Edit
        StoryFlow.Store.Error
        StoryFlow.Store.Index
        StoryFlow.Store.Node
        StoryFlow.Store.Query
        StoryFlow.Store.Row
        StoryFlow.Store.Schema
        StoryFlow.Store.Vault
        StoryFlow.Store.Write
    build-depends:
        , base          >=4.14 && <5
        , bytestring
        , containers
        , direct-sqlite
        , directory
        , filepath
        , sqlite-simple
        , storyflow-core
        , storyflow-md
        , text
        , time
        , toml-reader

test-suite storyflow-store-test
    import:           warnings, lang
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Spec.hs
    other-modules:
        StoryFlow.Store.AtomicSpec
        StoryFlow.Store.CreateSpec
        StoryFlow.Store.DeleteSpec
        StoryFlow.Store.EndToEndSpec
        StoryFlow.Store.ErrorSpec
        StoryFlow.Store.Fixtures
        StoryFlow.Store.IndexSpec
        StoryFlow.Store.InitSpec
        StoryFlow.Store.NodeSpec
        StoryFlow.Store.QuerySpec
        StoryFlow.Store.RebuildSpec
        StoryFlow.Store.SchemaSpec
        StoryFlow.Store.SearchSpec
        StoryFlow.Store.StaleSpec
        StoryFlow.Store.VaultSpec
        StoryFlow.Store.WriteSpec
        StoryFlow.StoreSpec
    build-depends:
        , base
        , bytestring
        , containers
        , directory
        , filepath
        , hspec
        , sqlite-simple
        , storyflow-core
        , storyflow-md
        , storyflow-store
        , temporary
        , text
        , time
        , toml-reader
