cabal-version:      3.4
name:               storyflow-types
version:            0.1.0.0
synopsis:           story-flow 型別註冊表的 TOML 載入層
license:            BSD-3-Clause
author:             Alchbees Studio
maintainer:         lhm.stu@gmail.com
build-type:         Simple

-- 註冊表隨程式碼版控,但 cabal install 之後的執行檔沒有原始碼樹的相對路徑。
-- 帶著它們走,執行期由 defaultRegistryDir 以 getDataDir 定位(func-0006 T2)。
data-files:         registry/*.toml

common warnings
    ghc-options: -Wall -Wcompat

common lang
    default-language:   GHC2021
    default-extensions:
        DerivingStrategies
        LambdaCase
        OverloadedStrings
        RecordWildCards
        StrictData

library
    import:           warnings, lang
    hs-source-dirs:   src
    exposed-modules:
        StoryFlow.Types.Loader
    other-modules:
        Paths_storyflow_types
    autogen-modules:
        Paths_storyflow_types
    build-depends:
        , base        >=4.14 && <5
        , bytestring
        , containers
        , directory
        , filepath
        , storyflow-core
        , text
        , toml-reader

test-suite storyflow-types-test
    import:           warnings, lang
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Spec.hs
    other-modules:
        StoryFlow.Types.LoaderSpec
    build-depends:
        , base
        , bytestring
        , directory
        , filepath
        , hspec
        , storyflow-core
        , storyflow-types
        , temporary
        , text
